name: Build, Push to ECR & Deploy to EKS

on:
  push:
    branches:
      - main   # or your branch

env:
  AWS_REGION: ap-south-1               # Your AWS region
  EKS_CLUSTER_NAME: java-maven         # Your EKS cluster name
  IMAGE_REPO_NAME: java                 # ECR repo name (must be created in ECR)
  IMAGE_TAG: latest                     # Image tag

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG .
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

      - name: Update kubeconfig for EKS cluster
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          EKS_CLUSTER_NAME: ${{ env.EKS_CLUSTER_NAME }}

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s-deploy.yml --validate=false
