name: Deploy Java App to EKS

on:
  push:
    branches:
      - main  # change to your branch if needed

jobs:
  deploy:
    name: Build & Deploy to EKS
    runs-on: ubuntu-latest

    env:
      ECR_REGISTRY: 641972036343.dkr.ecr.ap-southeast-1.amazonaws.com
      IMAGE_REPO_NAME: java
      IMAGE_TAG: latest
      EKS_CLUSTER_NAME: java-maven
      AWS_REGION: ap-southeast-1

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build Docker image
        run: |
          docker build -t $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG .

      - name: Push Docker image to Amazon ECR
        run: |
          docker push $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml
